### ISSUE TITLE
no library called "libcairo-2" was found

### ISSUE THREAD

**Issue by bhdicaire** [m-radzikowski/omnigraffle-stencil#4]
I updated PIP3 first and then installed without issue. Running omnigraffle-stencil --help provide the following output:

Traceback (most recent call last):
  File "/usr/local/bin/omnigraffle-stencil", line 5, in <module>
    from omnigraffle_stencil.converter import main
  File "/usr/local/lib/python3.9/site-packages/omnigraffle_stencil/converter.py", line 12, in <module>
    import cairosvg
  File "/usr/local/lib/python3.9/site-packages/cairosvg/__init__.py", line 42, in <module>
    from . import surface  # noqa isort:skip
  File "/usr/local/lib/python3.9/site-packages/cairosvg/surface.py", line 25, in <module>
    import cairocffi as cairo
  File "/usr/local/lib/python3.9/site-packages/cairocffi/__init__.py", line 48, in <module>
    cairo = dlopen(
  File "/usr/local/lib/python3.9/site-packages/cairocffi/__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': dlopen(libcairo.so.2, 2): image not found
cannot load library 'libcairo.2.dylib': dlopen(libcairo.2.dylib, 2): image not found
cannot load library 'libcairo-2.dll': dlopen(libcairo-2.dll, 2): image not found

This is my current PIP3 packages:

Package             Version
------------------- ---------
cairocffi           1.2.0
CairoSVG            2.4.2
certifi             2021.5.30
cffi                1.14.5
charset-normalizer  2.0.3
cssselect2          0.4.1
decorator           5.0.9
defusedxml          0.7.1
idna                3.2
omnigraffle-stencil 1.1.0
Pillow              8.2.0
pip                 21.2.2
PlexAPI             4.6.1
py                  1.10.0
pycparser           2.20
PyPDF2              1.26.0
PyYAML              5.4.1
requests            2.26.0
retry               0.9.2
setuptools          53.0.0
tinycss2            1.1.0
urllib3             1.26.6
webencodings        0.5.1
wheel               0.36.2

**Comment by m-radzikowski** [comment]
I see this library makes a ton of problems after quick google search. Can you tell what exactly commands did you run to install dependencies and on what system you are?

**Comment by bhdicaire** [comment]
I'm currently running MacOS Mojave 10.14.6 (e.g., current version). I'm pushing back reinstalling from scratch with Big Sur for couple of months. If we can't fixed this easily, I'll bite the bullet and start that operation. This is MacBook Pro (15-inch, 2018) 2.9 GHz Intel Core i9 with 32GB ram.

I upgraded PIP3 from 21.1.3 to 21.2.2 first with /usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip.

Then I installed omnigraffle-stencil with pip3 install omnigraffle-stencil. It looked like I installed the package before ... I got this output:
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: omnigraffle-stencil in /usr/local/lib/python3.9/site-packages (1.1.0)
Requirement already satisfied: cairosvg==2.4.2 in /usr/local/lib/python3.9/site-packages (from omnigraffle-stencil) (2.4.2)
Requirement already satisfied: PyPDF2==1.26.0 in /usr/local/lib/python3.9/site-packages (from omnigraffle-stencil) (1.26.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.9/site-packages (from cairosvg==2.4.2->omnigraffle-stencil) (8.2.0)
Requirement already satisfied: cairocffi in /usr/local/lib/python3.9/site-packages (from cairosvg==2.4.2->omnigraffle-stencil) (1.2.0)
Requirement already satisfied: tinycss2 in /usr/local/lib/python3.9/site-packages (from cairosvg==2.4.2->omnigraffle-stencil) (1.1.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.9/site-packages (from cairosvg==2.4.2->omnigraffle-stencil) (0.7.1)
Requirement already satisfied: cssselect2 in /usr/local/lib/python3.9/site-packages (from cairosvg==2.4.2->omnigraffle-stencil) (0.4.1)
Requirement already satisfied: cffi>=1.1.0 in /usr/local/lib/python3.9/site-packages (from cairocffi->cairosvg==2.4.2->omnigraffle-stencil) (1.14.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.1.0->cairocffi->cairosvg==2.4.2->omnigraffle-stencil) (2.20)
Requirement already satisfied: webencodings in /usr/local/lib/python3.9/site-packages (from cssselect2->cairosvg==2.4.2->omnigraffle-stencil) (0.5.1)

I tried to update CairoSVG with pip install CairoSVG with the following result:
pip install CairoSVG
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: CairoSVG in /usr/local/lib/python3.9/site-packages (2.4.2)
Requirement already satisfied: cssselect2 in /usr/local/lib/python3.9/site-packages (from CairoSVG) (0.4.1)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.9/site-packages (from CairoSVG) (0.7.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.9/site-packages (from CairoSVG) (8.2.0)
Requirement already satisfied: cairocffi in /usr/local/lib/python3.9/site-packages (from CairoSVG) (1.2.0)
Requirement already satisfied: tinycss2 in /usr/local/lib/python3.9/site-packages (from CairoSVG) (1.1.0)
Requirement already satisfied: cffi>=1.1.0 in /usr/local/lib/python3.9/site-packages (from cairocffi->CairoSVG) (1.14.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.1.0->cairocffi->CairoSVG) (2.20)
Requirement already satisfied: webencodings in /usr/local/lib/python3.9/site-packages (from cssselect2->CairoSVG) (0.5.1)
